config/routes.rb
Rails.application.routes.draw do
  root "homes#top"
  devise_for :users
  resources :users, only:[:show, :edit, :update]
  resources :gears, except:[:destroy]
  resources :plans do
    collection do
      post :gear_choice
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
  scope :mine, -> (user) {where(user_id: user)}
end

app/models/gear.rb
class Gear < ApplicationRecord
  belongs_to :user
  has_many :plan_gears
  has_many :plans, through: :plan_gears

  attachment :gear_image

  enum genre: {
    "テント・タープ": 0,
    "テーブル・チェア": 1,
    "調理道具": 2,
    "照明器具": 3,
    "焚き火道具": 4,
    "寝具": 5,
    "収納": 6,
    "燃料": 7,
    "その他": 8
  }

end

app/models/plan.rb
class Plan < ApplicationRecord
  with_options presence: true do
    validates :title
    validates :departure_date
    validates :return_date
    validates :place
    validates :member
  end

  belongs_to :user
  has_many :plan_gears, dependent: :destroy
  has_many :gears, through: :plan_gears

  def set_date(plan)
    plan.strftime("%m月%d日")
  end

  def set_time(plan)
    plan.strftime("%H時%M分")
  end
end

app/models/plan_gear.rb
class PlanGear < ApplicationRecord
  belongs_to :gear
  belongs_to :plan
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  attachment :profile_image

  has_many :gears, dependent: :destroy
  has_many :plans, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!

  def after_sign_in_path_for(resource) 
    user_path(current_user)
  end

  def after_sign_out_path_for(resource)
    root_path
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end

  def redirect_root
    redirect_to root_path unless user_signed_in?
  end
  
end

app/controllers/gears_controller.rb
class GearsController < ApplicationController
  before_action :set_gear, except:[:new, :create, :index]

  def new
    @gear = Gear.new
  end

  def create
    @gear = Gear.new(gear_params)
    @gear.user_id = current_user.id
    @gear.save
    redirect_to gears_path
  end

  def show
  end

  def index
    @gears = Gear.mine(current_user)
  end

  def edit
  end

  def update
    @gear.update(gear_params)
    redirect_to gear_path(@gear)
  end

  private
  def gear_params
    params.require(:gear).permit(:name, :introduction, :amount, :genre, :gear_image)
  end

  def set_gear
    @gear = Gear.find(params[:id])
  end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  skip_before_action :authenticate_user!
  def top
  end
end

app/controllers/plans_controller.rb
class PlansController < ApplicationController
  before_action :set_plan, except:[:new, :gear_choice, :create, :index]

  def new
    @plan = Plan.new
  end

  def gear_choice
    @plan = Plan.new(plan_params)
    @plan.plan_gears.build
  end

  def create
    @plan = Plan.new(plan_params)
    @plan.user_id = current_user.id
    @plan.save
    redirect_to plans_path
  end

  def show
    @gears = Gear.joins(:plan_gears).where(plan_gears: { plan_id: @plan.id })
  end

  def index
    @plans = Plan.mine(current_user)
  end

  def edit
  end

  def update
  end

  def destroy
  end

  private
  def plan_params
    params.require(:plan).permit(:title, :departure_date, :return_date, :place, :check_in_time, :check_out_time, :memo, :member, gear_ids: [])
  end

  def set_plan
    @plan = Plan.find(params[:id])
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only:[:show, :edit, :update]

  def show
  end

  def edit
  end

  def update
    @user.update(user_params)
    redirect_to user_path(@user)
  end


  private
  def user_params
    params.require(:user).permit(:name, :profile_image)
  end

  def set_user
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/gears_helper.rb
module GearsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/plans_helper.rb
module PlansHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/gears/_form.slim
.gear_form
  = form_with model: gear, local: true do |f|
    .gear_form__item
      p カテゴリー
      = f.select :genre, Gear.genres.keys.to_a, include_blank: "選択して下さい"
    .gear_form__item
      p ギア名
      = f.text_field :name
    .gear_form__item
      p 説明
      = f.text_area :introduction
    .gear_form__item
      p 数量
      = f.select :amount, options_for_select((1..20).to_a , gear.amount)
    .gear_form__item
      p ギア画像
      - if controller.action_name == "new"
        .attachment
          = attachment_image_tag gear, :gear_image, size: "100x100", fallback: "no_image_gear.png", class: "change_file"
          = f.attachment_field :gear_image
      - elsif controller.action_name == "edit"
        .attachment
          = attachment_image_tag gear, :gear_image, size: "100x100", fallback: "no_image_gear.png", class: "change_file"
          = f.attachment_field :gear_image, class: "myfile"
    .gear_form__item.gear_form__btn
      - if controller.action_name == "new"
        = f.submit "登録", class: "btn btn-success"
      - else controller.action_name == "edit"
        = f.submit "更新", class: "btn btn-success"

app/views/gears/_list.slim
- gears.each do |gear|
  .gear_list__item
    = link_to gear_path(gear)
      = attachment_image_tag gear, :gear_image, size: "50x50", fallback: "no_image_gear.png", class: "border"
      = gear.name

app/views/gears/edit.slim
= render "form", gear: @gear

app/views/gears/index.slim
.gear_list
  - Gear.genres.count.times do |i|
    - if @gears.exists?(genre: i)
      .gear_list__name
        p #{Gear.genres.key(i)}
        = render "list", gears: @gears.where(genre: i)

app/views/gears/new.slim
= render "form", gear: @gear

app/views/gears/show.slim
.gear_detail
  = attachment_image_tag @gear, :gear_image, size: "100x100", fallback: "no_image_gear.png"
  p ギア名
  = @gear.name
  p memo
  = @gear.introduction
  p 数量
  = @gear.amount

app/views/homes/top.html.slim
.content
  .title_area
    h1 CAMP NOTE
  .session_area
    .sign_in.session_btn
      = link_to "新規登録", new_user_registration_path, class: "btn btn-success btn-lg"
    .sign_up.session_btn
      = link_to "ログイン", new_user_session_path, class: "btn btn-success btn-lg"

app/views/layouts/_footer.slim
.footer_item
  = link_to gears_path do
    i.fas.fa-toolbox
.footer_item
  = link_to plans_path do
    i.fas.fa-campground
.footer_item
  = link_to user_path(current_user) do
    i.fas.fa-user-circle

app/views/layouts/_header.slim
- if controller.controller_name == "gears"
  - if controller.action_name == "new"
    h1 ギア登録
  - elsif controller.action_name == "show"
    h1 ギア詳細
    = link_to edit_gear_path do
      i.fas.fa-cog
  - elsif controller.action_name == "edit"
    h1 ギア編集
  - else
    h1 ギア一覧
    = link_to new_gear_path do
      i.fas.fa-plus-square
- elsif controller.controller_name == "plans"
  - if controller.action_name == "new"
    h1 計画作成
  - elsif controller.action_name == "show"
    h1 計画詳細
    = link_to edit_plan_path do
      i.fas.fa-cog
  - elsif controller.action_name == "edit"
    h1 計画編集
  - else
    h1 キャンプ計画一覧
    = link_to new_plan_path do
      i.fas.fa-plus-square
- elsif controller.controller_name == "users"
  - if controller.action_name == "edit"
    h1 ユーザー情報編集
  - else
    h1 ユーザー
    i.fas.fa-bars.menu_btn.open_btn
    i.fas.fa-times.menu_btn.close_btn.menu_btn_hide

app/views/layouts/_menu.slim
- if user_signed_in?
  .menu_list.
    .menu_list__item
      = link_to edit_user_path(current_user) do
        p ユーザー編集
    .menu_list__item
      = link_to destroy_user_session_path do
        p ログアウト

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      | CampNote
    meta[name="viewport" content="width=device-width,initial-scale=1"]
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    script[src="https://kit.fontawesome.com/5b5304f2df.js" crossorigin="anonymous"]
  body
    - unless controller.controller_name == "homes"
      header
        = render "layouts/header"
    .container
      = render "layouts/menu"
      = yield
    - unless controller.controller_name == "homes"
      footer
        = render "layouts/footer"
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'

app/views/plans/_gear.slim
.gear_list
  - Gear.genres.count.times do |i|
    - if gears.exists?(genre: i)
      .gear_list__name
        p #{Gear.genres.key(i)}
        = render "gears/list", gears: gears.where(genre: i)

app/views/plans/_schedule.slim
p #{plan.set_date(plan.departure_date)}〜#{plan.set_date(plan.return_date)}
= plan.title
p in#{plan.place}
p チェックイン
= plan.set_time(plan.check_in_time)
p チェックアウト
= plan.set_time(plan.check_out_time)
p 参加人数
p #{plan.member}人
p メモ
= plan.memo

app/views/plans/gear_choice.slim
.gear_choice_form
  = form_with model:@plan, local: true do |f|
    - if Gear.exists?(genre: 0)
      p テント・タープ
      = f.collection_check_boxes :gear_ids, Gear.where(genre: 0), :id, :name, include_hidden: false
    - if Gear.exists?(genre: 1)
      p テーブル・チェア
      = f.collection_check_boxes :gear_ids, Gear.where(genre: 1), :id, :name, include_hidden: false
    - if Gear.exists?(genre: 2)
      p 調理道具
      = f.collection_check_boxes :gear_ids, Gear.where(genre: 2), :id, :name, include_hidden: false
    - if Gear.exists?(genre: 3)
      p 照明器具
      = f.collection_check_boxes :gear_ids, Gear.where(genre: 3), :id, :name, include_hidden: false
    - if Gear.exists?(genre: 4)
      p 焚き火道具
      = f.collection_check_boxes :gear_ids, Gear.where(genre: 4), :id, :name, include_hidden: false
    - if Gear.exists?(genre: 5)
      p 寝具
      = f.collection_check_boxes :gear_ids, Gear.where(genre: 5), :id, :name, include_hidden: false
    - if Gear.exists?(genre: 6)
      p 収納
      = f.collection_check_boxes :gear_ids, Gear.where(genre: 6), :id, :name, include_hidden: false
    - if Gear.exists?(genre: 7)
      p 燃料
      = f.collection_check_boxes :gear_ids, Gear.where(genre: 7), :id, :name, include_hidden: false
    - if Gear.exists?(genre: 8)
      p その他
      = f.collection_check_boxes :gear_ids, Gear.where(genre: 8), :id, :name, include_hidden: false
    = f.hidden_field :title, :value => @plan.title
    = f.hidden_field :departure_date, :value => @plan.departure_date
    = f.hidden_field :return_date, :value => @plan.return_date
    = f.hidden_field :place, :value => @plan.place
    = f.hidden_field :check_in_time, :value => @plan.check_in_time
    = f.hidden_field :check_out_time, :value => @plan.check_out_time
    = f.hidden_field :member, :value => @plan.member
    = f.hidden_field :memo, :value => @plan.memo
    = f.submit "作成"

app/views/plans/index.slim
.plan_list
  - @plans.each do |plan|
    = link_to plan_path(plan)
      .plan_list__item
        = plan.set_date(plan.departure_date)
        = plan.title
        p in#{plan.place}

app/views/plans/new.slim
.plan_form
  = form_with model: @plan, url: gear_choice_plans_path, method: :post, local: true do |f|
    .plan_form__item
      p キャンプタイトル
      = f.text_field :title
    .plan_form__item
      p 日にち
      = f.date_field :departure_date
      = f.date_field :return_date
    .plan_form__item
      p チェックイン
      = f.time_select :check_in_time, start_hour: 9, end_hour: 20, minute_step: 30
    .plan_form__item
      p チェックアウト
      = f.time_select :check_out_time, start_hour: 9, end_hour: 20, minute_step: 30
    .plan_form__item
      p キャンプ場
      = f.text_field :place
    .plan_form__item
      p 参加人数
      = f.select :member, options_for_select((1..20).to_a, @plan.member)
    .plan_form__item
      p メモ
      = f.text_area :memo
    .plan_form__item.plan_form__btn
      = f.submit "ギア選択へ"

app/views/plans/show.slim
.detail_choice
  p.detail_choice__schedule スケジュール
  p.detail_choice__gear ギア
.plan_detail
  .plan_schedule
    = render "schedule", plan: @plan
  .plan_gear.hide
    = render "gear", gears: @gears

app/views/users/_profile.slim
.profile_area__avatar
  = attachment_image_tag user, :profile_image, size: "150x150", fallback: "no_image.jpg", class: "rounded-circle"
.profile_area__name
  = user.name

app/views/users/edit.slim
.user_edit_area
  .user_edit_area__form
    = form_with model:@user, local:true do |f|
      .user_edit_area__form__item
        .attachment.user_attachment
          = attachment_image_tag @user, :profile_image, size: "200x200", fallback: "no_image.jpg", class: "change_file rounded-circle"
          = f.attachment_field :profile_image, class: "myfile"
      .user_edit_area__form__item.user_edit_area__form__item__name
        = f.text_field :name, placeholder: "ユーザーネーム"
      .user_edit_area__form__item.user_edit_area__form__btn
        = f.submit "更新する", class:"btn btn-success"

app/views/users/show.slim
= render "layouts/menu"
  .user_show_area
    - if @user == current_user
      .profile_area
        = link_to edit_user_path(@user)
          = render "profile", user: @user
    - else
      .profile_area
        = render "profile", user: @user
    = link_to "ログアウト", destroy_user_session_path
= render "profile", user: @user